use crate::maths::polygonal::Polygonal;
use crate::register_problem;

register_problem!(45, "Triangular, pentagonal, and hexagonal", problem045);

pub fn problem045() -> String {
    // Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    // Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
    // Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
    // Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
    //
    // It can be verified that T285 = P165 = H143 = 40755.
    //
    // Find the next triangle number that is also pentagonal and hexagonal.
    let mut result = 0;
    for n in 286.. {
        let tn = u64::triangular(n);
        if u64::is_hexagonal(tn) && u64::is_pentagonal(tn) {
            result = tn;
            break;
        }
    }
    result.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_problem045() {
        let result = problem045();
        assert_eq!(result, "1533776805");
    }
}
