use crate::maths::polygonal;
use crate::register_problem;
use crate::utils::permutations::permutations;
use polygonal::is_polygonal;

fn find_cyclical() -> Option<Vec<u32>> {
    let t_polygonal = vec![3, 4, 5, 6, 7, 8];
    for permut in permutations(t_polygonal) {
        for n1 in 1010..10000 {
            if n1 % 100 > 9 && is_polygonal(n1, permut[0]) {
                for n2 in 10..100 {
                    if is_polygonal(n1 % 100 * 100 + n2, permut[1]) {
                        for n3 in 10..100 {
                            if is_polygonal(n2 % 100 * 100 + n3, permut[2]) {
                                for n4 in 10..100 {
                                    if is_polygonal(n3 % 100 * 100 + n4, permut[3]) {
                                        for n5 in 10..100 {
                                            if is_polygonal(n4 % 100 * 100 + n5, permut[4]) {
                                                let n6 = n1 / 100;
                                                if is_polygonal(n5 % 100 * 100 + n6, permut[5])
                                                {
                                                    let mut s = vec![
                                                        n1,
                                                        n1 % 100 * 100 + n2,
                                                        n2 % 100 * 100 + n3,
                                                        n3 % 100 * 100 + n4,
                                                        n4 % 100 * 100 + n5,
                                                        n5 % 100 * 100 + n6,
                                                    ];
                                                    s.sort();
                                                    return Some(s);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    None
}

register_problem!(61, "Cyclical figurate numbers", problem061);

pub fn problem061() -> String {
    // Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate
    // (polygonal) numbers and are generated by the following formulae:
    //
    //  Triangle        P3,n=n(n+1)/2       1, 3, 6, 10, 15, ...
    //  Square          P4,n=n2             1, 4, 9, 16, 25, ...
    //  Pentagonal      P5,n=n(3n−1)/2      1, 5, 12, 22, 35, ...
    //  Hexagonal       P6,n=n(2n−1)        1, 6, 15, 28, 45, ...
    //  Heptagonal      P7,n=n(5n−3)/2      1, 7, 18, 34, 55, ...
    //  Octagonal       P8,n=n(3n−2)        1, 8, 21, 40, 65, ...
    //
    // The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
    //
    //  - The set is cyclic, in that the last two digits of each number is the first two digits of the
    //    next number (including the last number with the first).
    //  - Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882),
    //    is represented by a different number in the set.
    //  - This is the only set of 4-digit numbers with this property.
    //
    // Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type:
    // triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different
    // number in the set.

    let solution = find_cyclical();
    let result = solution.unwrap().iter().sum::<u32>();
    result.to_string()
}
