use crate::maths::polygonal::{is_hexagonal, is_pentagonal, triangular};
use crate::maths::timer::ScopeTimer;

pub fn problem045() -> usize {
    let _timer = ScopeTimer::new("Problem 45 Triangular, pentagonal, and hexagonal", false);
    // Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    // Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
    // Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
    // Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
    //
    // It can be verified that T285 = P165 = H143 = 40755.
    //
    // Find the next triangle number that is also pentagonal and hexagonal.
    let mut result = 0;
    for n in 286.. {
        let tn = triangular(n);
        if is_hexagonal(tn) && is_pentagonal(tn) {
            result = tn;
            break;
        }
    }
    result
}
