use crate::maths::polygonal::{is_pentagonal, pentagonal};
use crate::register_problem;

register_problem!(44, "Pentagon numbers", problem044);

pub fn problem044() -> String {
    // Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    //
    //                              1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    //
    // It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    //
    // Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
    // D = |Pk − Pj| is minimised; what is the value of D?
    for i in 1..3000 {
        let pentagonal_i = pentagonal(i);
        for j in i + 1..3000 {
            let pentagonal_j = pentagonal(j);
            if is_pentagonal(pentagonal_j - pentagonal_i)
                && is_pentagonal(pentagonal_j + pentagonal_i)
            {
                return (pentagonal_j - pentagonal_i).to_string();
            }
        }
    }
    "".to_string()
}
