use crate::maths;
use crate::register_problem;
use maths::fibonacci::fibonacci_limit;

register_problem!(2, "Even Fibonacci numbers", problem002);

pub fn problem002() -> String {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    // find the sum of the even-valued terms.
    let mut solution: u64 = 0;
    for n in fibonacci_limit(4000000) {
        if n % 2 == 0 {
            solution += n;
        }
    }
    solution.to_string()
}
