use crate::maths;
use maths::timer;
use timer::ScopeTimer;

/*
gen fn fibonacci<N>(limite: N) -> N
where
    N: PrimInt + std::ops::DivAssign,
{
    let mut f0 = N::from(0);
    let mut f1 = N::from(1);
    yield f0;
    while f1 < limite {
        yield f1;
        let f2 = f0 + f1;
        f0 = f1;
        f1 = f2;
    }
}
*/

pub fn problem002() -> u64 {
    let _timer = ScopeTimer::new("Problem 2 Even Fibonacci numbers", true);
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    // find the sum of the even-valued terms.
    let mut solution: u64 = 0;
    for n in maths::fibonacci::fibonacci_limit(4000000u64) {
        if n % 2 == 0 {
            solution += n;
        }
    }
    println!("Solution 002: {}", solution);
    solution
}
